name: Build and Install Crosstool-NG

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  CROSSTOOL_NG_VERSION: 1.26.0

jobs:
  install:
    name: Build And Install Crosstool-NG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Pre-requires
        run: sudo apt install help2man libtool libtool-bin
      - name: Download Crosstool-NG And Extract
        run: |
          wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-${{ env.CROSSTOOL_NG_VERSION }}.tar.bz2
          tar --extract --bzip2 --file=crosstool-ng-${{ env.CROSSTOOL_NG_VERSION }}.tar.bz2
      - name: Build
        run: |
          cd crosstool-ng-${{ env.CROSSTOOL_NG_VERSION }}
          ./configure --prefix=$HOME/install/Crosstool-NG-1.26.0-${{ runner.os }}-${{ runner.arch }}
          make -j16
          sudo make install
          cd ..
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Crosstool-NG-1.26.0-${{ runner.os }}-${{ runner.arch }}
          path: ~/install


      

