name: 制作交叉工具链

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: '工具链打包名, 例如 aarch64-rpi5-linux-gcc13.2-glibc3.28'
        type: string
        required: true
      ct_ng_version:
        description: '指定 Crosstool-NG 的版本，例如: ''1.26.0'''
        type: string
        required: true
        default: 1.26.0
      system:
        description: '指定目标平台:'
        type: choice
        required: true
        default: ubuntu-latest
        options:
          - ubuntu-latest
          - ubuntu-22.04
          - ubuntu-20.04
          - windows-latest
          - windows-2022
          - windows-2019
          - macos-latest
          - macos-14
          - macos-13
          - macos-12

run-name: ${{ inputs.artifact_name }}-(${{ inputs.system }})

jobs:
  crosstool-ng:
    uses: ./.github/workflows/setup-crosstool-ng.yml
    with:
      version: ${{ inputs.ct_ng_version }}
      system: ${{ inputs.system }}

  make-tools:
    name: 制作交叉编译工具
    runs-on: ${{ inputs.system }}
    needs: crosstool-ng
    env:
      CROSSTOOL_NG_ARTIFACT_NAME: ${{ needs.crosstool-ng.outputs.artifact_name }}
      CROSSTOOL_NG_INSTALL_PARENT_DIR: ${{ needs.crosstool-ng.outputs.install_parent_directory }}
    steps:
      - uses: actions/checkout@v4

      - name: 加载 Crosstool-NG
        id: crosstool_ng
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.CROSSTOOL_NG_ARTIFACT_NAME }}
      
      - name: 设置 ct-ng 环境
        run: |
          sudo mkdir ${{ env.CROSSTOOL_NG_INSTALL_PARENT_DIR }}
          sudo tar --extract --gzip --directory ${{ env.CROSSTOOL_NG_INSTALL_PARENT_DIR }} \
              --file=${{ steps.crosstool_ng.outputs.download-path }}/${{ env.CROSSTOOL_NG_ARTIFACT_NAME }}.tar.gz
          echo PATH="${{ env.CROSSTOOL_NG_INSTALL_PARENT_DIR }}/${{ env.CROSSTOOL_NG_ARTIFACT_NAME }}/bin:$PATH" >> $GITHUB_ENV

      - name: 显示当前配置
        run: ct-ng show-config

      - name: 开始制作！
        run: |
          echo CROSSTOOL_NG_BUILD_DIR="$(pwd)" >> $GITHUB_ENV
          ct-ng build.16

      - name: 上传编译 log
        uses: actions/upload-artifact@v4
        with:
            name: build.log
            path: ${{ env.CROSSTOOL_NG_BUILD_DIR }}/build.log

      - name: 打包工具链
        run: |
          mkdir ~/${{ inputs.artifact_name }}
          cd ~/x-tools
          mv ./* ~/${{ inputs.artifact_name }}
          cd ~
          tar --create --gzip --file=${{ inputs.artifact_name }}.tar.gz ./${{ inputs.artifact_name }}

      - name: 上传工具链
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ~/${{ inputs.artifact_name }}.tar.gz
