name: 制作交叉工具链

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  crosstool-ng:
    uses: ./.github/workflows/setup-crosstool-ng.yml
    with:
      version: 1.26.0

  make-tools:
    name: 制作交叉编译工具
    runs-on: ubuntu-latest
    needs: crosstool-ng
    steps:
      - uses: actions/checkout@v4

      - name: 加载 Crosstool-NG
        id: crosstool_ng
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.crosstool-ng.outputs.artifact_name }}
      
      - name: 设置 ct-ng 环境
        run: |
          sudo mkdir ${{ needs.crosstool-ng.outputs.install_parent_directory }}
          sudo tar --extract --gzip --directory ${{ needs.crosstool-ng.outputs.install_parent_directory }} \
              --file=${{ steps.crosstool_ng.outputs.download-path }}/${{ needs.crosstool-ng.outputs.artifact_name }}.tar.gz
          echo PATH="${{ needs.crosstool-ng.outputs.install_parent_directory }}/${{ needs.crosstool-ng.outputs.artifact_name }}/bin:$PATH" >> $GITHUB_ENV

      - name: 显示当前配置
        run: ct-ng show-config

      - name: 开始制作！
        run: |
          echo CROSSTOOL_NG_BUILD_DIR="$(pwd)" >> $GITHUB_ENV
          ct-ng build.16

      - name: 上传编译 log
        uses: actions/upload-artifact@v4
        with:
            name: build-log-${{ github.event.release.name }}
            path: ${{ env.CROSSTOOL_NG_BUILD_DIR }}/build.log

      - name: 打包工具链
        run: |
          cd ~/x-tools
          tar --create --gzip --file=$HOME/${{ github.event.release.name }}.tar.gz ./

      - name: 上传工具链
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.release.name }}
          path: ~/${{ github.event.release.name }}.tar.gz
