name: 制作交叉工具链

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  CROSSTOOL_NG_VERSION: 1.26.0

jobs:
  make-tools:
    name: 制作交叉编译工具
    runs-on: ubuntu-latest
    steps:
      - name: 检出对应的代码
        uses: actions/checkout@v4

      - name: 设置环境变量
        run: echo CROSSTOOL_NG_PACKAGE_NAME="Crosstool-NG-${{ env.CROSSTOOL_NG_VERSION }}-${{ runner.os }}-${{ runner.arch }}" >> $GITHUB_ENV

      - name: 安装依赖
        run: sudo apt install help2man libtool libtool-bin

      - name: 下载 Crosstool-NG 并解压缩
        run: |
          wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-${{ env.CROSSTOOL_NG_VERSION }}.tar.bz2
          tar --extract --bzip2 --file=crosstool-ng-${{ env.CROSSTOOL_NG_VERSION }}.tar.bz2

      - name: 编译安装 Crosstool-NG
        run: |
          cd crosstool-ng-${{ env.CROSSTOOL_NG_VERSION }}
          ./configure --prefix=$HOME/install/${{ env.CROSSTOOL_NG_PACKAGE_NAME }}
          make -j16
          sudo make install
          cd ..
          echo PATH="$HOME/install/${{ env.CROSSTOOL_NG_PACKAGE_NAME }}/bin:$PATH" >> $GITHUB_ENV

      - name: 打包 Crosstool-NG
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CROSSTOOL_NG_PACKAGE_NAME }}
          path: ~/install

      - name: 显示当前配置
        run: ct-ng show-config

      - name: 开始制作！
        run: |
          echo CROSSTOOL_NG_BUILD_DIR="$(pwd)" >> $GITHUB_ENV
          ct-ng build.16

      - name: 上传编译 log
        uses: actions/upload-artifact@v4
        with:
            name: build-log-${{ github.event.release.name }}
            path: ${{ env.CROSSTOOL_NG_BUILD_DIR }}/build.log

      - name: 打包上传工具链
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.release.name }}
          path: ~/x-tools